export const descriptions = {}

descriptions['Colonialism'] = `
<p>The widespread distribution of the mass press brought ordinary citizens into the French colonial project for the first time. Perhaps as a consequence, French colonial ambitions grew dramatically towards the end of the 19th century with large annexations of African and Asian land. The textual data reveals intense newspaper coverage of colonial projects.  </p><p>In the 1860’s, Napoleon III began the French colonial policy of assimilation in Algeria, France’s first major foray into empire. Algeria’s centrality to French colonial identity appears on the graph; Algeria, the blue line, is consistently the most referenced colony in the five major French periodicals.    </p><p>The Congo closely follows Algeria in text popularity. The conquests of French explorer Pierre Savorgnan de Brazza in the early 1880’s brought a colonial fervor to the public; journalists recounted his adventures in a breathless, horse-race narrative, detailing territorial disputes with British explorer Henry Morton Stanley and appealing to French national pride. The precipitous increase in coverage of the Congo from 1881 to 1885 demonstrates the media sensation.</p><p>Coverage of France’s colonies in Asia suggests a sudden, sustained interest occurring in the late 30’s and 40’s, enough to rival coverage of Algeria. I am not familiar enough with the history to know why. As a guess, anti-colonial struggle grew in intensity throughout the pre and post-war period, and newspaper coverage might reflect metropolitan anxieties.  </p><p style="line-height:100%;margin-bottom:0"><br></p>
`;

descriptions['Colors'] =`
<p>Tracking the history of color reveals that the color spectrum we view as ordinary, the pastels and the neons, is the result of decades of experimentation and construction, much of it occurring in the 19th century. </p>
<p>A lecture by culture scholar _____ on the history of color inspired this search selection, “bleu clair” [light blue] and “bleu pastel” [pastel blue]. The chart tracks their slow rise to popularity. The first periodicals to mention the colors are mostly scientific journals, describing experimental processes or by-products. Towards the end of the 19th-century, the colors begin to appear in fashion contexts. </p>
`;

descriptions['Arts'] = `
<p>Studying trends in newspaper coverage reveals historical excitement over artistic movements. </p>
<p>Art deco, short for the French “arts decoratifs”, was a movement to shape the aesthetics of industry, architecture, and the individual. Art deco styles would later influence American architecture, including promotions for the Chicago World’s Fair and the exterior of the Empire State Building. The chart reveals two major spikes in coverage of the art deco movement, one around 1885, the other around 1925. There is a sudden drop in 1915, at the onset of the First World War. </p>
<p>From the textual context, it seems artistic competitions drove much of the excitement around the art deco movement; national design schools would offer prizes for the best industrial designs. As the charts and associated text indicate, these competitions gained extensive coverage in the press, perhaps part of a wider public fascination with industrial progress and boundary pushing. </p>
<p>The modernistic, flowery, inventive artwork of the “art nouveau” [new art] movement burst into mountainous prominence in the early 1900’s, but never seemed to reach the attention peaks of “les arts decoratifs”. I don’t know enough to say why; perhaps the French public viewed it as a sub-aesthetic within a larger movement to beautify daily life.</p>
`;

descriptions['Pastries'] = `
The history of culinary disciplines and French gastronomy includes the history of pastries. This three-way chart of pastries, brioche, and “viennoiserie” (the modern French word for buttery croissants and their derivatives) details the slow rise of “patisserie” [pastry] within French periodicals. Early discussion in 1865 includes a medical journal advocating for beeswax instead of animal fats for maintaining a wooden “pastry board”. Advice that has stood the test of time.
`;

descriptions['Scandal'] = `
<p>Alongside the earnest coverage of political scandal, the newspapers of the 19th century were eager for startling narratives to fill their “faits divers” [miscellaneous events] sections. Murders, poisonings, overt corruption, Manet’s nude paintings, all the news that’s fit to sell. The modern-day wall between “serious papers” and tabloids was far more fuzzy in the 19th and early 20th centuries. </p>
<p>A simple search for “scandal” over a given period is a simple way to detect moments of outrage and controversy, dramas that vivified opinions and sold newspapers. Grouping occurrences by month, or even day, is most effective to capture the coverage of fleeting scandals, although year-grouping is interesting. At risk of over-reading chaotic data, 1887 seems to have been a scandalous year.<br></p>
<p>A peak of note begins in 1892, when many papers begin referencing the Panama Canal scandal. The French financier Ferdinand de Lesseps, having brought the Suez Canal to a lucrative completion, raised funds to begin building the Panama Canal in 1881. The Central American climate proved more difficult to work in, though, leading to mass worker deaths and halting progress. To hide the canal’s difficulties, Lesseps bribed numerous public officials. </p>
<p>Lesseps’ frequent appearances reveal the immense sway the private sector held over France’s 19th-century colonial ambitions. As president of the Geographic Society, Lesseps was also the primary financer and promoter of explorer Pierre Savorgnan de Brazza’s subjugation of the Congo.</p>
`;

descriptions['Capitals'] = `
<p>This tool allows for searches over a single periodical, usefully limiting the scope. The Petit Journal was a prolific, populist journal that published consistently from 1863 to 1944, when the Petit Journal, like other journals that collaborated with the Nazi occupiers, shut down. The Petit Journal’s regular, frequent coverage offers a glimpse into public opinion.</p>
<p>The coverage of foreign cities hides a mountain of context and events that deserve close textual study. The chart plots occurrences of 5 foreign capitals, and the distant powers they often refer to, in the Petit Journal. London initially occupies the most text-space, by the mid 1930’s, however, Berlin, Washington, and Rome have mostly made up the distance. Tokyo never fully enters into the conversation, even during the runup to the Second World War. </p>
`;

descriptions['Far West'] = `
<p>This example tracks mentions of West Coast cities and is a bit of a personal curiosity. It reveals the stunning popularity of Portland in French periodicals, which is a good example of my app’s current limitations and the need to read the context surrounding a term’s appearance. </p> 
<p>The Gallica API offers support for “proximity” searches, and integrating this into the app would aid dramatically in pinpointing relevant occurrences. A search for “Portland” within 5 words from “Oregon” would tell a different story than the current graph, which mostly tracks the popularity of the Isle of Portland, England. Stay tuned! I’m still working on features.</p> 
<p>With a more unique city name like Seattle or Los Angeles, though, the story is clearer. Interest in Seattle first peaks around 1908, with many occurrences coming from advertisements for circuitous sailings to Seattle. Los Angeles follows shortly after, with an outlier peak in January 1910. Perhaps European interest in the West Coast is finally catching to the gold rush frenzy that swept through the United States in the early 1900’s? Or steamboats have become more affordable for the average French reader? </p> 
<p>Seattle in the 19th and early 20th centuries is also a chaotic place, and periodicals are happy to relate tales of revenge dynamitings, violent mobs, and other mayhem. Los Angeles is seemingly a bit calmer, with many mentions of air races. Interestingly, a French periodical from the port town of Marseille mentions Seattle more frequently than even the international edition of the New York Herald. </p> 

`;
